apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-applications
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: {{ .Values.repoURL }}
      revision: {{ .Values.repoBranch }}
      directories:
      - path: gitops_manifest/manifest/*
  template:
    metadata:
      name: '{{"{{"}}.path.basename{{"}}"}}'
    spec:
      project: infrastructure
      source:
        repoURL: {{ .Values.repoURL }}
        targetRevision: {{ .Values.repoBranch }}
        path: '{{"{{"}}.path.path{{"}}"}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{"{{"}}.path.basename{{"}}"}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true