apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-applications
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: {{ .Values.global.repoURL }}
      revision: gitops2
      directories:
      - path: gitops_manifest/manifest/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: infrastructure
      source:
        repoURL: {{ .Values.global.repoURL }}
        targetRevision: gitops2
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true