apiVersion: v1
stringData:
  Name: gitops-repo
  type: git
  url: "{{ .Values.repoURL }}"
kind: Secret
metadata:
  name: gitops_repo
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque