apiVersion: v1
kind: Secret
metadata:
  name: gitops-repo
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  Name: gitops-repo
  type: git
  url: "{{ .Values.repoURL }}"
type: Opaque