---
- name: Deploy IBM Operator Catalog
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ cluster_kubeconfig }}"
    wait: yes
    definition: "{{ lookup('file', 'files/ibm-operator-catalog.yaml') | from_yaml }}"
...
