---
- name: Deploy IBM API Connect Subscription
  kubernetes.core.k8s:
    state: present
    api_key: "{{ ocpApiKey }}"
    wait: yes
    definition: "{{ lookup('template', 'templates/ibm-api-connect-sub.j2') }}"
...
