apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: must-gather
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  source:
    path: "{{ .Values.global.manifest_dir }}/must-gather"
    repoURL: "{{ .Values.global.repoURL }}"
    targetRevision: "{{ .Values.global.repoBranch }}"
    helm:
      valueFiles:
        - values.yaml
  project: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true