---
- name: Deploy IBM Datapower Subscription
  kubernetes.core.k8s:
    state: present
    api_key: "{{ ocpApiKey }}"
    wait: yes
    definition: "{{ lookup('template', 'templates/ibm-datapower-sub.j2') }}"
...
